export const message = {
	PASSWORD_VALIDATION:
		'Password must meet complexity requirements: at least one lowercase, one uppercase, one digit, one special character, and min length of 8 characters.',
	REGISTER_SUCCESS: 'User created successfully',
	LOGIN_SUCCESS: 'User loggedIn successfully.',
	LOGIN_INVALID: 'Invalid username or password',
	UNAUTHORIZED: 'Unauthorized',
	LIST_SUCCESS: 'User list fetch successfully',
	UPDATE_USER: 'User updated successfully',
	EMAIL_USED: 'Email already exist',
	DETAIL_NOT_FOUND: 'Record not found with given id',
	UPDATE_USER_PROFILE: 'User Profile updated suceessfully',
	USER_DETAIL_FETCHED: 'User detail succuessfully fetched',
	CHANNEL_NAME_REQUIRED: 'Channel name is a required field',
	CHANNEL_CREATE_SUCCESS: 'Channel created successfully',
	CHANNEL_FIND_ALL_SUCCESS: 'Channel list fetched successfully',
	CHANNEL_DETAIL_FETCHED: 'Channel detail fetched successfully',
	CHANNEL_UPDATE_SUCCESS: 'Channel details update successfully',
	CHANNEL_DELETE_SUCCESS: 'Channel deleted successfully',
	VIDEO_NAME_REQUIRED: 'Video name or url is a required field',
	VIDEO_CREATE_SUCCESS: 'Video uploaded successfully',
	CHANNEL_NOT_FOUND: 'Channel not found with given id',
	VIDEO_LIST_SUCCESS: 'Video list fetch successfully',
	APPROVAL_SUCCESS: 'Video approved successfully',
	REJECTED_SUCCESS: 'Video rejected successfully',
	VIDEO_DETAIL_FETCHED: 'Video detail successfully fetched',
	UPDATE_VIDEO: 'Video data updated successfully',
	DELETE_VIDEO: 'Video Deleted successfully',
	IMAGE_INVALID: 'Image is not supported',
	SONG_INVALID: 'Song is not supported',
	VIDEO_INVALID: 'Video is not supported',
	FILE_INVALID: 'File not supported',
	VIDEO_UPLOAD_FAILED: 'Failed to upload video',
	TOKEN_EXPIRED: 'Token expired',
	NO_CHANNELS_FOR_USER: 'No channels found for this user.',
	VIDEO_NOT_FOUND: 'Video not found',
	REQUIRED_FEILD: 'Required field missing',
	VIDEO_COMMENT_NOT_FOUND: 'Video comment not found',
	VIDEO_COMMENTS_SUCCESS: 'Video comments fetch successfully',
	FEEDBACK_SUCCESS: 'Successfully added the feedback',
	FEEDBACK_UPDATE: 'Successfully updated the feedback',
	FEEDBACK_REMOVE: 'Successfully removed the feedback',
};
